version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ec2_scripts/set_up
      timeout: 300
      runas: sudo
  AfterInstall:
    - location: ec2_scripts/run
      timeout: 300
      runas: sudo